---
name: CGI-Application-Plugin-Stream
version: 2.05
author:
  - Jason Purdy <Jason@Purdy.INFO>
abstract: Plugin that adds file streaming support to CGI::Application
license: perl
requires:
  CGI::Application: 3.21
  File::Basename: 1
  File::MMagic: 0
  FileHandle: 1.22
  Test::More: 0
provides:
  CGI::Application::Plugin::Stream:
    file: lib/CGI/Application/Plugin/Stream.pm
    version: 2.05
generated_by: Module::Build version 0.26
