--- #YAML:1.0
name: CGI-Application-Plugin-Stream
version: 2.00
license: perl
distribution_type: module
requires:
  CGI::Application: 3.21
  File::Basename: 1
  File::MMagic: 0
  FileHandle: 1.22
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  CGI::Application::Plugin::Stream:
    file: lib/CGI/Application/Plugin/Stream.pm
    version: 2.00
generated_by: Module::Build version 0.21
